const REQUEST_USER_LIST = 'REQUEST_USER_LIST';
const SUCCESS_USER_LIST = 'SUCCESS_USER_LIST';
const ERROR_USER_LIST = 'ERROR_USER_LIST';

export { REQUEST_USER_LIST, SUCCESS_USER_LIST, ERROR_USER_LIST };
