const REQUEST_TIMER_VIEW = 'REQUEST_TIMER_VIEW';
const SUCCESS_TIMER_VIEW = 'SUCCESS_TIMER_VIEW';
const ERROR_TIMER_VIEW = 'ERROR_TIMER_VIEW';

export { REQUEST_TIMER_VIEW, SUCCESS_TIMER_VIEW, ERROR_TIMER_VIEW };
