const REQUEST_TIMER_ADD = 'REQUEST_TIMER_ADD';
const SUCCESS_TIMER_ADD = 'SUCCESS_TIMER_ADD';
const ERROR_TIMER_ADD = 'ERROR_TIMER_ADD';

export { REQUEST_TIMER_ADD, SUCCESS_TIMER_ADD, ERROR_TIMER_ADD };
