const REQUEST_TIMER_LIST = 'REQUEST_TIMER_LIST';
const SUCCESS_TIMER_LIST = 'SUCCESS_TIMER_LIST';
const ERROR_TIMER_LIST = 'ERROR_TIMER_LIST';

export { REQUEST_TIMER_LIST, SUCCESS_TIMER_LIST, ERROR_TIMER_LIST };
